### ISSUE TITLE
What is the data license?

### ISSUE THREAD

**Issue by todrobbins** [alexlitel/congresstweets-automator#1]
Hi @alexlitel,

I was wondering what the data license is for `users-filtered.json`, `users.json`.  It's a useful bit of JSON and would love to repurpose it.

**Comment by alexlitel** [comment]
The data, like the rest of the repo, falls under the MIT license. The `users.json` dataset heavily borrows from the @unitedstates/congress-legislators project, which is public domain.

**Comment by todrobbins** [comment]
Thanks!
